# wrangler.toml
name = 'lolpedia'
account_id = "c8f6d4b0da936f2b193a16e91eed0d10"
compatibility_date = "2025-11-10"

[assets]
  directory = "out"
  # aquí están los archivos exportados
  
routes = [
  { pattern = "lolpedia.workers.dev", custom_domain = false }
]